list: $/eugenetolok/telegram/models/step/columns.yaml
modelClass: EugeneTolok\Telegram\Models\Step
title: Step
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eugenetolok/telegram/step/update/:id'
