list: $/eugenetolok/telegram/models/dialog/columns.yaml
modelClass: EugeneTolok\Telegram\Models\Dialog
title: Dialog
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eugenetolok/telegram/dialog/update/:id'
